// <auto-generated />
namespace Migrations.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201706301615218_add-Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
